// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

#ifndef PROTOBUF_INCLUDED_responses_2eproto
#define PROTOBUF_INCLUDED_responses_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_responses_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_responses_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_responses_2eproto();
namespace communication {
namespace responses {
class DirectoryVerification;
class DirectoryVerificationDefaultTypeInternal;
extern DirectoryVerificationDefaultTypeInternal _DirectoryVerification_default_instance_;
}  // namespace responses
}  // namespace communication
namespace google {
namespace protobuf {
template<> ::communication::responses::DirectoryVerification* Arena::CreateMaybeMessage<::communication::responses::DirectoryVerification>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace communication {
namespace responses {

// ===================================================================

class DirectoryVerification :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:communication.responses.DirectoryVerification) */ {
 public:
  DirectoryVerification();
  virtual ~DirectoryVerification();

  DirectoryVerification(const DirectoryVerification& from);

  inline DirectoryVerification& operator=(const DirectoryVerification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DirectoryVerification(DirectoryVerification&& from) noexcept
    : DirectoryVerification() {
    *this = ::std::move(from);
  }

  inline DirectoryVerification& operator=(DirectoryVerification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DirectoryVerification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DirectoryVerification* internal_default_instance() {
    return reinterpret_cast<const DirectoryVerification*>(
               &_DirectoryVerification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DirectoryVerification* other);
  friend void swap(DirectoryVerification& a, DirectoryVerification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DirectoryVerification* New() const final {
    return CreateMaybeMessage<DirectoryVerification>(nullptr);
  }

  DirectoryVerification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DirectoryVerification>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DirectoryVerification& from);
  void MergeFrom(const DirectoryVerification& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DirectoryVerification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string differents = 2;
  int differents_size() const;
  void clear_differents();
  static const int kDifferentsFieldNumber = 2;
  const ::std::string& differents(int index) const;
  ::std::string* mutable_differents(int index);
  void set_differents(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_differents(int index, ::std::string&& value);
  #endif
  void set_differents(int index, const char* value);
  void set_differents(int index, const char* value, size_t size);
  ::std::string* add_differents();
  void add_differents(const ::std::string& value);
  #if LANG_CXX11
  void add_differents(::std::string&& value);
  #endif
  void add_differents(const char* value);
  void add_differents(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& differents() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_differents();

  // string root_name = 1;
  void clear_root_name();
  static const int kRootNameFieldNumber = 1;
  const ::std::string& root_name() const;
  void set_root_name(const ::std::string& value);
  #if LANG_CXX11
  void set_root_name(::std::string&& value);
  #endif
  void set_root_name(const char* value);
  void set_root_name(const char* value, size_t size);
  ::std::string* mutable_root_name();
  ::std::string* release_root_name();
  void set_allocated_root_name(::std::string* root_name);

  // @@protoc_insertion_point(class_scope:communication.responses.DirectoryVerification)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField<::std::string> differents_;
  ::google::protobuf::internal::ArenaStringPtr root_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_responses_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DirectoryVerification

// string root_name = 1;
inline void DirectoryVerification::clear_root_name() {
  root_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DirectoryVerification::root_name() const {
  // @@protoc_insertion_point(field_get:communication.responses.DirectoryVerification.root_name)
  return root_name_.GetNoArena();
}
inline void DirectoryVerification::set_root_name(const ::std::string& value) {
  
  root_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:communication.responses.DirectoryVerification.root_name)
}
#if LANG_CXX11
inline void DirectoryVerification::set_root_name(::std::string&& value) {
  
  root_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:communication.responses.DirectoryVerification.root_name)
}
#endif
inline void DirectoryVerification::set_root_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  root_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:communication.responses.DirectoryVerification.root_name)
}
inline void DirectoryVerification::set_root_name(const char* value, size_t size) {
  
  root_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:communication.responses.DirectoryVerification.root_name)
}
inline ::std::string* DirectoryVerification::mutable_root_name() {
  
  // @@protoc_insertion_point(field_mutable:communication.responses.DirectoryVerification.root_name)
  return root_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DirectoryVerification::release_root_name() {
  // @@protoc_insertion_point(field_release:communication.responses.DirectoryVerification.root_name)
  
  return root_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DirectoryVerification::set_allocated_root_name(::std::string* root_name) {
  if (root_name != nullptr) {
    
  } else {
    
  }
  root_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), root_name);
  // @@protoc_insertion_point(field_set_allocated:communication.responses.DirectoryVerification.root_name)
}

// repeated string differents = 2;
inline int DirectoryVerification::differents_size() const {
  return differents_.size();
}
inline void DirectoryVerification::clear_differents() {
  differents_.Clear();
}
inline const ::std::string& DirectoryVerification::differents(int index) const {
  // @@protoc_insertion_point(field_get:communication.responses.DirectoryVerification.differents)
  return differents_.Get(index);
}
inline ::std::string* DirectoryVerification::mutable_differents(int index) {
  // @@protoc_insertion_point(field_mutable:communication.responses.DirectoryVerification.differents)
  return differents_.Mutable(index);
}
inline void DirectoryVerification::set_differents(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:communication.responses.DirectoryVerification.differents)
  differents_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void DirectoryVerification::set_differents(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:communication.responses.DirectoryVerification.differents)
  differents_.Mutable(index)->assign(std::move(value));
}
#endif
inline void DirectoryVerification::set_differents(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  differents_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:communication.responses.DirectoryVerification.differents)
}
inline void DirectoryVerification::set_differents(int index, const char* value, size_t size) {
  differents_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:communication.responses.DirectoryVerification.differents)
}
inline ::std::string* DirectoryVerification::add_differents() {
  // @@protoc_insertion_point(field_add_mutable:communication.responses.DirectoryVerification.differents)
  return differents_.Add();
}
inline void DirectoryVerification::add_differents(const ::std::string& value) {
  differents_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:communication.responses.DirectoryVerification.differents)
}
#if LANG_CXX11
inline void DirectoryVerification::add_differents(::std::string&& value) {
  differents_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:communication.responses.DirectoryVerification.differents)
}
#endif
inline void DirectoryVerification::add_differents(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  differents_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:communication.responses.DirectoryVerification.differents)
}
inline void DirectoryVerification::add_differents(const char* value, size_t size) {
  differents_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:communication.responses.DirectoryVerification.differents)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
DirectoryVerification::differents() const {
  // @@protoc_insertion_point(field_list:communication.responses.DirectoryVerification.differents)
  return differents_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
DirectoryVerification::mutable_differents() {
  // @@protoc_insertion_point(field_mutable_list:communication.responses.DirectoryVerification.differents)
  return &differents_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace responses
}  // namespace communication

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_responses_2eproto
