// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

#include "responses.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace communication {
namespace responses {
class DirectoryVerificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DirectoryVerification> _instance;
} _DirectoryVerification_default_instance_;
}  // namespace responses
}  // namespace communication
static void InitDefaultsDirectoryVerification_responses_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::communication::responses::_DirectoryVerification_default_instance_;
    new (ptr) ::communication::responses::DirectoryVerification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::communication::responses::DirectoryVerification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DirectoryVerification_responses_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDirectoryVerification_responses_2eproto}, {}};

void InitDefaults_responses_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_DirectoryVerification_responses_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_responses_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_responses_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_responses_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_responses_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::communication::responses::DirectoryVerification, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::communication::responses::DirectoryVerification, root_name_),
  PROTOBUF_FIELD_OFFSET(::communication::responses::DirectoryVerification, differents_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::communication::responses::DirectoryVerification)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::communication::responses::_DirectoryVerification_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_responses_2eproto = {
  {}, AddDescriptors_responses_2eproto, "responses.proto", schemas,
  file_default_instances, TableStruct_responses_2eproto::offsets,
  file_level_metadata_responses_2eproto, 1, file_level_enum_descriptors_responses_2eproto, file_level_service_descriptors_responses_2eproto,
};

const char descriptor_table_protodef_responses_2eproto[] =
  "\n\017responses.proto\022\027communication.respons"
  "es\">\n\025DirectoryVerification\022\021\n\troot_name"
  "\030\001 \001(\t\022\022\n\ndifferents\030\002 \003(\tb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_responses_2eproto = {
  false, InitDefaults_responses_2eproto, 
  descriptor_table_protodef_responses_2eproto,
  "responses.proto", &assign_descriptors_table_responses_2eproto, 114,
};

void AddDescriptors_responses_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_responses_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_responses_2eproto = []() { AddDescriptors_responses_2eproto(); return true; }();
namespace communication {
namespace responses {

// ===================================================================

void DirectoryVerification::InitAsDefaultInstance() {
}
class DirectoryVerification::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DirectoryVerification::kRootNameFieldNumber;
const int DirectoryVerification::kDifferentsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DirectoryVerification::DirectoryVerification()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:communication.responses.DirectoryVerification)
}
DirectoryVerification::DirectoryVerification(const DirectoryVerification& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      differents_(from.differents_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  root_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.root_name().size() > 0) {
    root_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.root_name_);
  }
  // @@protoc_insertion_point(copy_constructor:communication.responses.DirectoryVerification)
}

void DirectoryVerification::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_DirectoryVerification_responses_2eproto.base);
  root_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

DirectoryVerification::~DirectoryVerification() {
  // @@protoc_insertion_point(destructor:communication.responses.DirectoryVerification)
  SharedDtor();
}

void DirectoryVerification::SharedDtor() {
  root_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DirectoryVerification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DirectoryVerification& DirectoryVerification::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_DirectoryVerification_responses_2eproto.base);
  return *internal_default_instance();
}


void DirectoryVerification::Clear() {
// @@protoc_insertion_point(message_clear_start:communication.responses.DirectoryVerification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  differents_.Clear();
  root_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DirectoryVerification::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<DirectoryVerification*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string root_name = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("communication.responses.DirectoryVerification.root_name");
        object = msg->mutable_root_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // repeated string differents = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          ctx->extra_parse_data().SetFieldName("communication.responses.DirectoryVerification.differents");
          object = msg->add_differents();
          if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
            parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
            goto string_till_end;
          }
          GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
          ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
          ptr += size;
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 18 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DirectoryVerification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:communication.responses.DirectoryVerification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string root_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_root_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->root_name().data(), static_cast<int>(this->root_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "communication.responses.DirectoryVerification.root_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string differents = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_differents()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->differents(this->differents_size() - 1).data(),
            static_cast<int>(this->differents(this->differents_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "communication.responses.DirectoryVerification.differents"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:communication.responses.DirectoryVerification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:communication.responses.DirectoryVerification)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DirectoryVerification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:communication.responses.DirectoryVerification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string root_name = 1;
  if (this->root_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->root_name().data(), static_cast<int>(this->root_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "communication.responses.DirectoryVerification.root_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->root_name(), output);
  }

  // repeated string differents = 2;
  for (int i = 0, n = this->differents_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->differents(i).data(), static_cast<int>(this->differents(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "communication.responses.DirectoryVerification.differents");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->differents(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:communication.responses.DirectoryVerification)
}

::google::protobuf::uint8* DirectoryVerification::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:communication.responses.DirectoryVerification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string root_name = 1;
  if (this->root_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->root_name().data(), static_cast<int>(this->root_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "communication.responses.DirectoryVerification.root_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->root_name(), target);
  }

  // repeated string differents = 2;
  for (int i = 0, n = this->differents_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->differents(i).data(), static_cast<int>(this->differents(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "communication.responses.DirectoryVerification.differents");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->differents(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:communication.responses.DirectoryVerification)
  return target;
}

size_t DirectoryVerification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:communication.responses.DirectoryVerification)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string differents = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->differents_size());
  for (int i = 0, n = this->differents_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->differents(i));
  }

  // string root_name = 1;
  if (this->root_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->root_name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DirectoryVerification::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:communication.responses.DirectoryVerification)
  GOOGLE_DCHECK_NE(&from, this);
  const DirectoryVerification* source =
      ::google::protobuf::DynamicCastToGenerated<DirectoryVerification>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:communication.responses.DirectoryVerification)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:communication.responses.DirectoryVerification)
    MergeFrom(*source);
  }
}

void DirectoryVerification::MergeFrom(const DirectoryVerification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:communication.responses.DirectoryVerification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  differents_.MergeFrom(from.differents_);
  if (from.root_name().size() > 0) {

    root_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.root_name_);
  }
}

void DirectoryVerification::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:communication.responses.DirectoryVerification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DirectoryVerification::CopyFrom(const DirectoryVerification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:communication.responses.DirectoryVerification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DirectoryVerification::IsInitialized() const {
  return true;
}

void DirectoryVerification::Swap(DirectoryVerification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DirectoryVerification::InternalSwap(DirectoryVerification* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  differents_.InternalSwap(CastToBase(&other->differents_));
  root_name_.Swap(&other->root_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata DirectoryVerification::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_responses_2eproto);
  return ::file_level_metadata_responses_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace responses
}  // namespace communication
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::communication::responses::DirectoryVerification* Arena::CreateMaybeMessage< ::communication::responses::DirectoryVerification >(Arena* arena) {
  return Arena::CreateInternal< ::communication::responses::DirectoryVerification >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
