# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: responses.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='responses.proto',
  package='communication.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fresponses.proto\x12\x17\x63ommunication.responses\">\n\x15\x44irectoryVerification\x12\x11\n\troot_name\x18\x01 \x01(\t\x12\x12\n\ndifferents\x18\x02 \x03(\tb\x06proto3')
)




_DIRECTORYVERIFICATION = _descriptor.Descriptor(
  name='DirectoryVerification',
  full_name='communication.responses.DirectoryVerification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root_name', full_name='communication.responses.DirectoryVerification.root_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='differents', full_name='communication.responses.DirectoryVerification.differents', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['DirectoryVerification'] = _DIRECTORYVERIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DirectoryVerification = _reflection.GeneratedProtocolMessageType('DirectoryVerification', (_message.Message,), dict(
  DESCRIPTOR = _DIRECTORYVERIFICATION,
  __module__ = 'responses_pb2'
  # @@protoc_insertion_point(class_scope:communication.responses.DirectoryVerification)
  ))
_sym_db.RegisterMessage(DirectoryVerification)


# @@protoc_insertion_point(module_scope)
