# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='requests.proto',
  package='communication.request',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0erequests.proto\x12\x15\x63ommunication.request\")\n\nTokenLogin\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xa9\x01\n\x15\x44irectoryVerification\x12\x11\n\troot_name\x18\x01 \x01(\t\x12L\n\x08\x63ontents\x18\x02 \x03(\x0b\x32:.communication.request.DirectoryVerification.ContentsEntry\x1a/\n\rContentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"B\n\x08\x46ileDiff\x12\x15\n\rrelative_path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\x62\x06proto3')
)




_TOKENLOGIN = _descriptor.Descriptor(
  name='TokenLogin',
  full_name='communication.request.TokenLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='communication.request.TokenLogin.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='communication.request.TokenLogin.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=82,
)


_DIRECTORYVERIFICATION_CONTENTSENTRY = _descriptor.Descriptor(
  name='ContentsEntry',
  full_name='communication.request.DirectoryVerification.ContentsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communication.request.DirectoryVerification.ContentsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communication.request.DirectoryVerification.ContentsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=254,
)

_DIRECTORYVERIFICATION = _descriptor.Descriptor(
  name='DirectoryVerification',
  full_name='communication.request.DirectoryVerification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root_name', full_name='communication.request.DirectoryVerification.root_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='communication.request.DirectoryVerification.contents', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DIRECTORYVERIFICATION_CONTENTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=254,
)


_FILEDIFF = _descriptor.Descriptor(
  name='FileDiff',
  full_name='communication.request.FileDiff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='relative_path', full_name='communication.request.FileDiff.relative_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='communication.request.FileDiff.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='communication.request.FileDiff.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=322,
)

_DIRECTORYVERIFICATION_CONTENTSENTRY.containing_type = _DIRECTORYVERIFICATION
_DIRECTORYVERIFICATION.fields_by_name['contents'].message_type = _DIRECTORYVERIFICATION_CONTENTSENTRY
DESCRIPTOR.message_types_by_name['TokenLogin'] = _TOKENLOGIN
DESCRIPTOR.message_types_by_name['DirectoryVerification'] = _DIRECTORYVERIFICATION
DESCRIPTOR.message_types_by_name['FileDiff'] = _FILEDIFF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenLogin = _reflection.GeneratedProtocolMessageType('TokenLogin', (_message.Message,), dict(
  DESCRIPTOR = _TOKENLOGIN,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:communication.request.TokenLogin)
  ))
_sym_db.RegisterMessage(TokenLogin)

DirectoryVerification = _reflection.GeneratedProtocolMessageType('DirectoryVerification', (_message.Message,), dict(

  ContentsEntry = _reflection.GeneratedProtocolMessageType('ContentsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DIRECTORYVERIFICATION_CONTENTSENTRY,
    __module__ = 'requests_pb2'
    # @@protoc_insertion_point(class_scope:communication.request.DirectoryVerification.ContentsEntry)
    ))
  ,
  DESCRIPTOR = _DIRECTORYVERIFICATION,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:communication.request.DirectoryVerification)
  ))
_sym_db.RegisterMessage(DirectoryVerification)
_sym_db.RegisterMessage(DirectoryVerification.ContentsEntry)

FileDiff = _reflection.GeneratedProtocolMessageType('FileDiff', (_message.Message,), dict(
  DESCRIPTOR = _FILEDIFF,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:communication.request.FileDiff)
  ))
_sym_db.RegisterMessage(FileDiff)


_DIRECTORYVERIFICATION_CONTENTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
